export enum NotificationType {
  EXPIRY_90 = 'EXPIRY_90',
  EXPIRY_60 = 'EXPIRY_60',
  EXPIRY_30 = 'EXPIRY_30',
  EXPIRY_7 = 'EXPIRY_7',
  EXPIRY_0 = 'EXPIRY_0',
  REMINDER_15 = 'REMINDER_15',
  REMINDER_30 = 'REMINDER_30',
  WARNING = 'WARNING',
  ASSIGNED = 'ASSIGNED',
  INSPECTION_SCHEDULED = 'INSPECTION_SCHEDULED',
}
